language: generic
os: linux
env: All unit and widget tests
before_script:
  # install pre-compiled flutter
  - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
  - FLUTTER_CHANNEL=stable
  - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL}
  - wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz > /dev/null && rm flutter.tar.xz
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

  # install flown
  pub global activate -path .
script:
  - flown --arch vanilla --name vanilla
  - cd vanilla
  - flutter test