name: flown
description: Clone a Flutter app from a url. Any local dependencies are installed with the app package.
version: 0.1.0
homepage: https://github.com/mmcc007/flown
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  yaml: ^2.1.15
  args: ^1.5.0
  yamlicious: ^0.1.0
  path: ^1.6.2

dev_dependencies:
  test: ^1.3.4

executables:
  flown: flown
