name: flown
description: Clone a flutter app from a url.
version: 0.0.1
homepage: https://www.example.com
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  yaml: ^2.1.15
  args: ^1.5.0
  yamlicious: ^0.1.0

dev_dependencies:
  test: ^1.3.4

executables:
  flown: flown
